site_name: MicroRaft
site_description: "MicroRaft: Java implementation of the Raft consensus algorithm"
site_url: https://microraft.io
site_author: "Ensar Basri Kahveci"
copyright: 'MicroRaft, 2021. Open-sourced by <a href="https://twitter.com/metanet" target="_blank">Ensar Basri Kahveci</a>.<br/>MicroRaft is not affiliated, associated, endorsed by, or in any way officially connected with<br/>Facebook, or any of its subsidiaries or its affiliates.'
docs_dir: src
use_directory_urls: true
theme: flatly
google_analytics: ["UA-485423-8", "MicroRaft"]

plugins:
  - search

markdown_extensions:
  - attr_list
  - fenced_code

nav:
  - "Docs":
      - Setup: "docs/setup.md"
      - Main Abstractions: "docs/main-abstractions.md"
      - Configuration: "docs/configuration.md"
      - "Tutorial: Building an Atomic Register": "docs/tutorial-building-an-atomic-register.md"
      - Resiliency and Fault Tolerance: "docs/resiliency-and-fault-tolerance.md"
      - Monitoring: "docs/monitoring.md"
      - "Javadoc 0.4-SNAPSHOT": "javadoc/0.4-SNAPSHOT/index.html"
      - "Javadoc 0.3": "javadoc/0.3/index.html"
      - "Javadoc 0.1": "javadoc/0.1/index.html"
      - Release Notes: "docs/release-notes.md"
      - Roadmap: "docs/roadmap.md"
  - "Blog":
      - "September 8, 2021 | Today a Raft Follower, Tomorrow a Raft Leader": "blog/2021-09-08-today-a-raft-follower-tomorrow-a-raft-leader.md"
      - "September 3, 2021 | Introducing MicroRaft": "blog/2021-09-03-introducing-microraft.md"
      - "All Blog Posts": "blog"
  - "Github": "https://github.com/MicroRaft/MicroRaft"
  - "Twitter": "https://twitter.com/MicroRaft"
